### PR TITLE
Add null handling to methods

### LINKED ISSUE #336: Handle null checks on methods
Following the introduction of null check tests on PRs, a large number of null check failures happen on Test Toolkit, which skews the results being displayed and does not paint a fun portrait of the toolkit.

Go through the toolkit and improve this by doing some null handling on all engine methods.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #336 

 ### Test files

 ### Changelog

 ### Additional comments
This does reduce the number of `null-handling` errors by about 100 on the default stuff. Need to keep reducing on the other parts of the core for Test-Toolkit just to help reduce the noise but this is a good start.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Review by michaelhoehn — APPROVED** [review]
LGTM

**Pull request merged**
