### PR TITLE
PushPullCompare from file setting to exit the adapter

### LINKED ISSUE #354: InteropabilityTest_Engine: Add Exit command call to the adapter for the PushPullCompare method
#### Description:

Adding call to the Exit command added in https://github.com/BHoM/BHoM_Adapter/issues/302 to the end of the Test_Toolkit run to clean up the adapter.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Adapter/pull/303

 ### Issues addressed by this PR

 Closes #354 

 

Adding call to the Exit command to the adapter as a final clean-up step after the PushPullCompare has been run.

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Review by peterjamesnugent — CHANGES_REQUESTED** [review]
Happy the functionality works - I've tested this on Lusas.

I think we should update the description that it will exit the software upon completion.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check complaince

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check null-handling

**Review by peterjamesnugent — APPROVED** [review]
LGTM.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check null-handling

**Pull request merged**
