### PR TITLE
Aligning with changes in BHoMAdapter Refactoring Level 04

### LINKED ISSUE #108: Interoperability_Test: Update to adapter lvl04 refactoring
Not as major as the rest of the refactoring, but following the comment chain here:
https://github.com/BHoM/Test_Toolkit/pull/6#discussion_r365197412

There will need to be an update based on BHoM_Adapter changes by the 24th January.

@IsakNaslundBh I've assigned us both first one to do it can unassign the other 👍

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Depends on 
https://github.com/BHoM/BHoM_Engine/pull/1371
https://github.com/BHoM/BHoM_Adapter/pull/164
https://github.com/BHoM/BHoM_UI/pull/167

- If you use Grasshopper: https://github.com/BHoM/Grasshopper_Toolkit/pull/440
- If you use Excel: https://github.com/BHoM/Excel_Toolkit/pull/172
- If you use Dynamo: https://github.com/BHoM/Dynamo_Toolkit/pull/188

- If your Toolkit needs Socket_Toolkit: https://github.com/BHoM/Socket_Toolkit/pull/57
- If your Toolkit needs Mongo_Toolkit: https://github.com/BHoM/Mongo_Toolkit/pull/82

- If you want the Adapter components to be automatically upgraded to their new version in your test scripts: https://github.com/BHoM/Versioning_Toolkit/pull/8

 ### Issues addressed by this PR
Fixes #108 

 ### Test files

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
Sorry, maybe a little sneaky addition, but should have been there if available before, adding the NewModel execute before running each set. Something quite relaxing watching Robot wipe models and push new elements:
Pushing bars Robot Testsets

**Comment by FraserGreenroyd** [comment]
> Big part of the diff seems to actually be solving a different problem?

See @IsakNaslundBh being sneaky :wink:

**Comment by IsakNaslundBh** [comment]
> > Big part of the diff seems to actually be solving a different problem?
> 
> See @IsakNaslundBh being sneaky 😉

Yeah, sorry about that, but was a small change that was enabled by the refactoring and more or less everything being blocked, I added it in..

**Comment by epignatelli** [comment]
> > > Big part of the diff seems to actually be solving a different problem?
> > 
> > 
> > See @IsakNaslundBh being sneaky 😉
> 
> Yeah, sorry about that, but was a small change that was enabled by the refactoring and more or less everything being blocked, I added it in..

gif

**Pull request merged**
