### PR TITLE
Postbuild of Test_Engine fixed

### LINKED ISSUE #478: Test_Engine: PostBuild fails due to an attempt to copy KellermanSoftware.Compare-NET-Objects
#### Description:

As in the title, dependency on `KellermanSoftware.Compare-NET-Objects.dll` got removed in [this commit](https://github.com/BHoM/Test_Toolkit/commit/28c0dd2634c2c74662f544706f367b592619d182) after switching to Diffing_Engine. The postbuild was not updated accordingly, which causes build exceptions in case given assembly has not been generated by some other project previously built.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #478

 

 ### Test files

Install fresh Alpha and try building.

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Review by peterjamesnugent — APPROVED** [review]
Built against latest alpha with no issues and the `KellermanSoftware.Compare-NET-Objects.dll` is present in ProgramData.

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check project-compliance
@BHoMBot check copyright-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check project-compliance
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check project-compliance
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
