### PR TITLE
Project compliance updated.

### LINKED ISSUE #414: CSProject compliance
Needs fixing for this repo.

In CodeCompliance_oM\CodeComplianceTest_oM.csproj

Inner results:
	Project reference for 'Analytical_oM' should be set to not copy local - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/Project-References-and-Build-Paths
	Project reference for 'Analytical_oM' should set specific version as false - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/Project-References-and-Build-Paths
	Project reference for 'BHoM' should set specific version as false - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/Project-References-and-Build-Paths
	Project reference for 'BHoM_Adapter' should set specific version as false - For more information see https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/Project-References-and-Build-Paths

### PR DESCRIPTION
**Pull request by kprusicka**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #414

### CODE REVIEW

**Comment by kprusicka** [comment]
@BHoMBot Check copyright-compliance
@BHoMBot Check null-handling
@BHoMBot Check project-compliance

**Review by FraserGreenroyd — APPROVED** [review]
Checks are passing, compliance meets broken rules from the issue, happy to merge.

**Comment by kprusicka** [comment]
Thank you @BHoMBot

**Comment by FraserGreenroyd** [comment]
Tack sa mycket @BHoMBot

**Pull request merged**
