### PR TITLE
Simplify output message file paths

### LINKED ISSUE #182: ComplianceTest_Engine: Furthe tweaking to the report messaging.
#### Description:

Really like the shortened improved reporting for the compliance test. Makes it far more readable. Some further minor suggestions to improve it even further:

image

Basically:

- Get rid of all auto generated stuff for the location that does not correspond to an actual "file path".
- The Assert failed thing does not add that much to the user, good if it could get removed.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #182 

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
image

Proof of message being simplified.

**Comment by IsakNaslundBh** [comment]
> image
> 
> Proof of message being simplified.

Should not

 `- in Test_Toolkit\Test_Engine\CodeComplianceTest_Engine\Query\GetClass.cs at line 36, column 32`

really be

  `- in Test_Toolkit\CodeComplianceTest_Engine\Query\GetClass.cs at line 36, column 32`

**Comment by FraserGreenroyd** [comment]
> Should not
> 
> `- in Test_Toolkit\Test_Engine\CodeComplianceTest_Engine\Query\GetClass.cs at line 36, column 32`
> 
> really be
> 
> `- in Test_Toolkit\CodeComplianceTest_Engine\Query\GetClass.cs at line 36, column 32`

Unfortunately we only have access to the `ProjectName` (`Test_Toolkit`) so where we slightly move files to allow the testing to take place we can end up with the extra folder but we have lost the irrelevant starting bits.

We could split it based on the slash and take only the elements after 2, but only if we can be certain that 100% of the time we want to do that.

**Comment by IsakNaslundBh** [comment]
> > Should not
> > `- in Test_Toolkit\Test_Engine\CodeComplianceTest_Engine\Query\GetClass.cs at line 36, column 32`
> > really be
> > `- in Test_Toolkit\CodeComplianceTest_Engine\Query\GetClass.cs at line 36, column 32`
> 
> Unfortunately we only have access to the `ProjectName` (`Test_Toolkit`) so where we slightly move files to allow the testing to take place we can end up with the extra folder but we have lost the irrelevant starting bits.
> 
> We could split it based on the slash and take only the elements after 2, but only if we can be certain that 100% of the time we want to do that.

As "Test_Engine" is something generated by the Test_Toolkit/CI somehow, we must be able to get rid of it, no? I hear what you say about moving files, and extra folders, but I assume that is done is a consistent way, so you should be able to assume what extra folders have been created etc?

**Comment by FraserGreenroyd** [comment]
> As "Test_Engine" is something generated by the Test_Toolkit/CI somehow, we must be able to get rid of it, no? I hear what you say about moving files, and extra folders, but I assume that is done is a consistent way, so you should be able to assume what extra folders have been created etc?

It's created by the Powershell scripts which sit outside the testing framework and are not currently accessible to the bit of framework which runs the tests as a result.

**Comment by IsakNaslundBh** [comment]
> It's created by the Powershell scripts which sit outside the testing framework and are not currently accessible to the bit of framework which runs the tests as a result.

But those are powershell scripts created by us, that we have control over what they do? If so, any extra folders should be predictable?

**Comment by FraserGreenroyd** [comment]
> But those are powershell scripts created by us, that we have control over what they do? If so, any extra folders should be predictable?

And if ever we changed them and how they work we would have to change this code as well, introducing a risk that we change one and forget the other and end up with errors in our results. I am aiming to avoid duplication of code where possible.

**Comment by IsakNaslundBh** [comment]
> And if ever we changed them and how they work we would have to change this code as well, introducing a risk that we change one and forget the other and end up with errors in our results. I am aiming to avoid duplication of code where possible.

I get that. Any possibility for the test toolkit to know what the powershell scripts are doing? Or any change to compare the filename in the repo with the one being run? Or any change to extract this from the solution file?

**Comment by al-fisher** [comment]
> Any possibility for the test toolkit to know what the powershell scripts are doing?

Yep - plan to further integrate powershell and test toolkit all in C# (also potentially as part of VS_UI)
Not a small task. But has been discussed for future improvements

**Comment by FraserGreenroyd** [comment]
Eventually perhaps, but not with the current scope of framework we have available @IsakNaslundBh - as per @al-fisher comment basically.

**Pull request merged**
