### PR TITLE
Check for whether objects implementing an IElement interface have accessible IElement methods

### LINKED ISSUE #139: Test_Toolkit: Compliance checks for required extension methods
#### Description:
In relation to migrating and giving `IElement` some structure, there should be compliance checks that ensures that the required extension methods exists for classes implementing `IElement`

Issue outlining which methods are required:
https://github.com/BHoM/BHoM_Engine/issues/1470

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #139

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 21737262999

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by Tom-Kingstone — APPROVED** [review]
Approve on code inspection, good work @FraserGreenroyd 😄

**Pull request merged**
