### PR TITLE
Update Copyright Header to 2021

### LINKED ISSUE #312: Compliance of BHoM file Copyright Headers
All BHoM `.cs` files need to contain the current [BHoM copyright statement](https://github.com/BHoM/BHoM/blob/master/COPYRIGHT_HEADER.txt) as their header.

For more information see [Code Compliance - HasValidCopyright](https://github.com/BHoM/documentation/wiki/HasValidCopyright)

### PR DESCRIPTION
**Pull request by BHoMBot**
Closes #312

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Comment by FraserGreenroyd** [comment]
This LGTM, I just need to investigate the potential impact on @adecler existing PR which I'll do tomorrow.

**Review by adecler — CHANGES_REQUESTED** [review]
Tested programmatically with [this script](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/05_CI%20CD/TestCopyright.gh?csf=1&web=1&e=CLWa9r). Two files need fixing:

```
Test_Toolkit\InteroperabilityTest_oM\PushPullCompareConfig.cs
Test_Toolkit\InteroperabilityTest_oM\Enums\ComparerType.cs
```

Both have a double copyright header.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Review by adecler — APPROVED** [review]
I reran the test and all looks good now

**Pull request merged**
