### PR TITLE
Kellerman replaced with Diffing

### LINKED ISSUE #473: Change equality comparison from Kellerman to Diffing
#### Description:

In some workflows it would be desirable to leverage full capacity of Diffing when comparing objects (e.g. to ignore chosen Revit parameters etc.) - this would require replacing Kellerman equality comparison with Diffing.

Discussed in the past, I believe we have agreement this is a right move, so I will action.

FYI @alelom @FraserGreenroyd @IsakNaslundBh

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Engine/pull/3338

 ### Issues addressed by this PR

 Closes #473

 

 ### Test files

Not entirely sure how to test, I did check if geometry UTs run the same as on `main`, file uploaded on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FTest%5FToolkit%2F%23474%2DReplaceKellermanWithDiffing&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4). Will also run `unit-tests` check, happy for recommendations concerning any further testing.

 ### Changelog

 ### Additional comments

I made sure the removed methods were not used anywhere outside of this repo by reviewing the results of following queries:
https://github.com/search?q=org%3ABHoM%20isequal&type=code
https://github.com/search?q=org%3ABurohappoldengineering%20isequal&type=code
https://github.com/search?q=org%3ABHoM%20DifferentProperties&type=code
https://github.com/search?q=org%3ABurohappoldengineering%20DifferentProperties&type=code

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot fix project file ref. 24298883442

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by alelom — APPROVED** [review]
Looks good from a code perspective.

**Pull request merged**
