### PR TITLE
Upgrade System.Runtime.CompilerServices.Unsafe.dll to 5.0.0.0

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #

 

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting force checks on: code-compliance, documentation-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Review by adecler — APPROVED** [review]
The code changes make sense and are in line with the other PRs in this set.

**Pull request merged**
