### PR TITLE
Update compliance of objects to include IObject

### LINKED ISSUE #433: IObject compliance
- [x] BH.oM.Test.NUnit.TestSuite
 - [x] BH.oM.Test.NUnit.TestRun
 - [x] BH.oM.Test.NUnit.TestCase
 - [x] BH.oM.Test.NUnit.Settings
 - [x] BH.oM.Test.NUnit.Setting
 - [x] BH.oM.Test.NUnit.Property
 - [x] BH.oM.Test.NUnit.Properties
 - [x] BH.oM.Test.NUnit.Failure
 - [x] BH.oM.Test.NUnit.Environment
 - [x] BH.oM.Test.NUnit.Assertions
 - [x] BH.oM.Test.NUnit.Assertion
 - [x] BH.oM.Test.NUnit.NUnitTest

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #433

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check null-handling
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 13083470548

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check null-handling
@BHoMBot check project-compliance
@BHoMBot check serialisation

**Review by IsakNaslundBh — APPROVED** [review]
All looks good to me, cant really see any problems.

Ofc, good to get @alelom s opinion as well, given it is his work, but happy to approve from my end

**Pull request merged**
