### PR TITLE
Start of milestone changes for 8.0 

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 

Update assembly file version to 8.0.0.0 and AssemblyVersion to 8.0.0.0
Remove previous version attributes for 8.0
Update expected assembly versions in project compliance checks

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Review by adecler — DISMISSED** [review]
The changes are as described. All projects have been updated.

**Comment by IsakNaslundBh** [comment]
@BHoMBot copyright-compliance
@BHoMBot check null-handling
@BHoMBot check project-compliance
@BHoMBot check serialisation

**Comment by IsakNaslundBh** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by adecler — APPROVED** [review]
Re-approving now the compliance issues have been fixed

**Pull request merged**
