### PR TITLE
UnitTest_Engine: Add methods for help creation of unit test datasets

### LINKED ISSUE #366: UnitTest_Engine: Add method to help create compliant dataset for Unittest .ci checks
#### Description:

As title states. Add methods that help the setup and generation of files that are correctly set up for the ci unit tests

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 Closes #366

 

Adding methods wo help create proper, compliant UnitTest Datasets and a method to put them in the correct folder of a repo.

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot fix copyright headers ref. 4842079508

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Review by FraserGreenroyd — APPROVED** [review]
This is a good addition, have reviewed with @IsakNaslundBh and am happy for this to be deployed to help others generate the unit test sets! Tack så mycket @IsakNaslundBh 😄

**Pull request merged**
