### PR TITLE
Fix multi output check

### LINKED ISSUE #342: MultiOutput compliance check gives false errors for more generic output types with more than one argument
#### Description:

The check for multiOutput compliance gives false errors if one of the output is a generic type with more than one argument, for example a dictionary. It seems as the check is relying on the amount of commas in the type name after "Output<" which gives wrong results for cases like this.

See https://github.com/BHoM/BHoM_Engine/pull/2504 for example

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #342 

Fixes some checks that were running on `Objects` files FYI @peterjamesnugent 

#### Test Files
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Test_Toolkit/%23343-MultiOutputComplianceCheck?csf=1&web=1&e=1MKMPy

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Review by peterjamesnugent — COMMENTED** [review]
I can get `Engine.Structures.Compute.Integrate` to pass.

However, when I delete one of the `MultiOutput` attributes in the line below - it still passes the check when you would expect the check to fail:
https://github.com/BHoM/BHoM_Engine/blob/abe8e7afefcb489b0cae7092178c5eca5e489e71/Structure_Engine/Compute/Integrate.cs#L142

I've added the script to the OP.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@peterjamesnugent thanks for the review - I noticed the script was slightly inaccurate (my fault, I didn't walk you through how to use the component properly) so I've updated it and put it in the folder you provided (thanks also for that!).

I did however find an issue which should now have been resolved in the last commit :smile:

**Review by jamesramsden-bh — APPROVED** [review]
Tested against provided script, all fine.

**Review by IsakNaslundBh — APPROVED** [review]
Tested with testscript. Looks fine my end as well

**Review by peterjamesnugent — APPROVED** [review]
LGTM!

**Pull request merged**
